catboost:
  iterations: 1000
  learning_rate: 0.01
  loss_function: "CrossEntropy"
  random_state: 42
  verbose: 100

train:
  train_data_path: data/train.csv
  path_to_save: models/model.cbm

infer:
  test_data_path: data/test.csv
  model_path: models/model.cbm
  path_to_save_pred: data/predict.csv

mlflow:
  tracking_uri: http://127.0.0.1:5000
  exp_name: first_experiment
  is_mlflow_logging: False

server:
  model_name: catboost_classifier
  model_stage: 1
